version: '3.8'

networks:
  ceph:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  ceph-mon:
    image: ceph/daemon:v6.0.0-stable-6.0-pacific-centos-8
    container_name: ceph-mon
    command: "mon"
    environment:
      - MON_IP=172.20.0.10
      - CEPH_PUBLIC_NETWORK=172.20.0.0/16
      - MON_NAME=ceph-mon
    volumes:
      - ./ceph-data/lib:/var/lib/ceph
      - ./ceph-data/etc:/etc/ceph
      - ./ceph-data/logs:/var/log/ceph
    networks:
      ceph:
        ipv4_address: 172.20.0.10
    restart: unless-stopped

  ceph-mgr:
    image: ceph/daemon:v6.0.0-stable-6.0-pacific-centos-8
    container_name: ceph-mgr
    command: "mgr"
    environment:
      - MGR_NAME=ceph-mgr
    volumes:
      - ./ceph-data/lib:/var/lib/ceph
      - ./ceph-data/etc:/etc/ceph
      - ./ceph-data/logs:/var/log/ceph
    networks:
      - ceph
    depends_on:
      - ceph-mon
    ports:
      - "8443:8443"
    restart: unless-stopped

  ceph-osd1:
    image: ceph/daemon:v6.0.0-stable-6.0-pacific-centos-8
    container_name: ceph-osd1
    privileged: true
    command: "osd_directory"
    environment:
      - OSD_TYPE=directory
    volumes:
      - ./ceph-data/lib:/var/lib/ceph
      - ./ceph-data/etc:/etc/ceph
      - ./ceph-data/logs:/var/log/ceph
      - ./ceph-data/osd1:/var/lib/ceph/osd
    networks:
      - ceph
    depends_on:
      - ceph-mon
    restart: unless-stopped

  ceph-osd2:
    image: ceph/daemon:v6.0.0-stable-6.0-pacific-centos-8
    container_name: ceph-osd2
    privileged: true
    command: "osd_directory"
    environment:
      - OSD_TYPE=directory
    volumes:
      - ./ceph-data/lib:/var/lib/ceph
      - ./ceph-data/etc:/etc/ceph
      - ./ceph-data/logs:/var/log/ceph
      - ./ceph-data/osd2:/var/lib/ceph/osd
    networks:
      - ceph
    depends_on:
      - ceph-mon
    restart: unless-stopped

  ceph-rgw:
    image: ceph/daemon:v6.0.0-stable-6.0-pacific-centos-8
    container_name: ceph-rgw
    command: "rgw"
    environment:
      - RGW_NAME=ceph-rgw
      - RGW_CIVETWEB_PORT=8080
    volumes:
      - ./ceph-data/lib:/var/lib/ceph
      - ./ceph-data/etc:/etc/ceph
      - ./ceph-data/logs:/var/log/ceph
    networks:
      - ceph
    depends_on:
      - ceph-mon
      - ceph-mgr
      - ceph-osd1
      - ceph-osd2
    ports:
      - "8080:8080"
    restart: unless-stopped